### PR TITLE
Specify the build type in the conan command

### PR DESCRIPTION
**Pull request by php1ic**
Start working on #20

We should also update the CI to do Debug and Release builds

### CODE REVIEW

**Comment by php1ic** [comment]
Is the `ci/circleci: build-run` check hard coded? If so, it will need to be changed or removed now the different Debug and Release CI builds have been added.

**Comment by ferdymercury** [comment]
Thanks, debug build works now!

@martukas might know wrt build-run

**Review by ferdymercury — APPROVED** [review]
Thanks!

**Comment by ferdymercury** [comment]
@php1ic maybe you need to set the default build type? See https://discuss.circleci.com/t/using-pipeline-parameters/34980/8

**Comment by php1ic** [comment]
Any preference on the default build type?

**Comment by ferdymercury** [comment]
> Any preference on the default build type?

Release I'd say

**Comment by ferdymercury** [comment]
Thanks! Hmm it seems there is still the build-run thing without suffix. Maybe it does not like having this "matrix" parameter?

**Comment by php1ic** [comment]
Some searching suggests that "expected" checks are setup and configured by someone with push access to the branch

https://stackoverflow.com/questions/39043691/github-pull-request-checks
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches

Can you see anything in Settings->Branches for this repo?

**Comment by ferdymercury** [comment]
> Can you see anything in Settings->Branches for this repo?

Nope. I only have access to Settings tab. So I guess we need @martukas assistance.

**Pull request merged**
